stages:
  - build

build:
  stage: build
  tags:
    - windows
  before_script:
    - CHCP 65001
  
  script:
    - ./msvc_build.bat
  artifacts:
    paths:
      - msvc/*.exe
      - msvc/glut32.dll



