stages:
  - build

variables:
  BUILD_CONFIG: 'Release'

build:
  stage: build
  tags:
    - windows
  script:
    - ./msvc_build.bat

  after_script:
    - mv "Bubblebobble_Termproject_28/$env:BUILD_CONFIG/" ./
    - cp background.jpg "$env:BUILD_CONFIG/"
  artifacts:
    paths:
      - "$env:BUILD_CONFIG/*"

build_linux:
  image: gcc
  stage: build
  tags:
    - shared
  before_script:
    - echo "$PWD"
    - apt-get update -qq && apt-get install -y -qq cmake freeglut3-dev libfreeimage-dev
    - mkdir build
  script:
    - echo "$PWD"
    - cd build && cmake ../
    - echo "$PWD"
    - cmake --build . --target all -- -j 4
    - echo "$PWD"
  after_script:
    - echo "$PWD"
    - mv build/bin ./ && mv build/lib ./ && cp background.jpg bin/
  only: 
    - master
  artifacts:
    when: on_success
    paths:
      - "**/*"
      # - "bin/*"
      # - "lib/*"
      # - "background.jpg"
