stages:
  - build

variables:
  BUILD_CONFIG: 'Release'

build:
  stage: build
  tags:
    - windows

  script:
    - ./msvc_build.bat

  after_script:
    - mv "Bubblebobble_Termproject_28/$env:BUILD_CONFIG/" ./
    - cp background.jpg "$env:BUILD_CONFIG/"
  artifacts:
    paths:
      - "$env:BUILD_CONFIG/*"
