stages:
  - build

variables:
  BUILD_CONFIG: 'Debug'

build:
  stage: build
  tags:
    - windows

  script:
    - ./msvc_build.bat
    - mv ab/ab/%BUILD_CONFIG% ./
  artifacts:
    paths:
      - "%BUILD_CONFIG%/*"
