stages:
  - build

variables:
  BUILD_CONFIG: 'Release'

build:
  stage: build
  tags:
    - windows
  script:
    - ./msvc_build.bat

  after_script:
    - mv "Bubblebobble_Termproject_28/$env:BUILD_CONFIG/" ./
    - cp background.jpg "$env:BUILD_CONFIG/"
  artifacts:
    paths:
      - "$env:BUILD_CONFIG/*"

build_linux:
  image: gcc
  stage: build
  tags:
    - shared
  before_script:
    - apt-get update -qq && apt-get install -y -qq cmake freeglut3-dev libfreeimage-dev
    - mkdir build
  script:
    - cd build && cmake ../
    - cmake --build . --target all -- -j 4
  after_script:
    - mv build/bin ../ && mv build/lib ../ && cp background.jpg ./bin/
  when: manual
  only: 
    - master
  artifacts:
    when: on_success
    paths:
      - "bin/*"
      - "lib/*"
      - "background.jpg"
