stages:
  - build

variables:
  BUILD_CONFIG: 'Release'

build:
  stage: build
  tags:
    - windows

  script:
    - cd ab/ab
    - ../../msvc_build.bat
  artifacts:
    paths:
      - "$env:BUILD_CONFIG/*"
