stages:
  - build

variables:
  BUILD_CONFIG: 'Release'

build:
  stage: build
  tags:
    - windows
  script:
    - ./msvc_build.bat

  after_script:
    - mv "Bubblebobble_Termproject_28/$env:BUILD_CONFIG/" ./
    - cp background.jpg "$env:BUILD_CONFIG/"
    - cp player0.png "$env:BUILD_CONFIG/"
    - cp player1.png "$env:BUILD_CONFIG/"

  artifacts:
    paths:
      - "$env:BUILD_CONFIG/*"

build_linux:
  image: "$CI_REGISTRY_IMAGE"
  stage: build
  tags:
    - shared
  before_script:
    - mkdir build
  script:
    - cd build && cmake ../
    - cmake --build . --target all -- -j 4
  after_script:
    - mv build/bin ./ && mv build/lib ./ && cp background.jpg bin/ && cp player0.png bin/ && cp player1.png bin/
  only: 
    - master
  artifacts:
    when: on_success
    paths:
      - "bin/*"
      - "lib/*"
